### ISSUE TITLE
Missing web factor type

### ISSUE THREAD

**Issue by pete911** [wearefair/okta-auth#14]
web factor type is missing - https://developer.okta.com/docs/reference/api/factors/#factor-type
I am currently working on implementing this, just adding issue as placeholder to create PR against.

**Comment by jowparks** [comment]
@pete911  did you ever get a PR working? I know some special stuff had to be done with the `aws-okta` library here 
https://github.com/segmentio/aws-okta/blob/2b49403a747b636794b5d31245ee28d31a7bdb51/lib/duo.go#L107-L116

**Comment by pete911** [comment]
@jowparks no, I have not ... I have moved jobs and haven't used this library since ...
